### ISSUE TITLE
希望大家来稱讚維基倉教

### ISSUE THREAD

**Issue by maaalawu** [mrhso/Cangjie_Note#5]
維基教科書•倉頡至今見不到一個共開的客觀的讚譽，希望大家一起来讚美維基倉教。

馬拉錘（無敵公式1-0.1^n作者）跟他們深度合作，也希望大家一同對其讚美。

**Comment by mrhso** [comment]
![image](https://user-images.githubusercontent.com/13294467/136663688-630fc8a9-b6f2-4746-8e06-1943f5ccec86.png)
